# Generated by Django 5.1.3 on 2024-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип свечи')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Производитель')),
                ('size', models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер свечи')),
                ('diameter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Диаметр свечи')),
                ('length', models.CharField(blank=True, max_length=200, null=True, verbose_name='Длинна свечи')),
                ('quantity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество свечей')),
                ('burning_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время горения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'ordering': ['price'],
            },
        ),
    ]
